packages:
  - native
  - mono/apps/*
  - mono/docs/*
  - mono/examples/*

catalog:
  '@biomejs/biome': 2.3.10
  astro: 5.16.6
  turbo: 2.7.1
  typescript: 5.9.3

onlyBuiltDependencies:
  - '@sentry/cli'
  - esbuild
  - sharp
