packages:
  - native
  - mono/apps/*
  - mono/docs/*
  - mono/examples/*

catalog:
  '@biomejs/biome': 2.3.4
  astro: 5.15.4
  turbo: 2.6.0
  typescript: 5.9.3

onlyBuiltDependencies:
  - '@sentry/cli'
  - esbuild
  - sharp
