packages:
  - native
  - mono/apps/*
  - mono/docs/*
  - mono/examples/*

catalog:
  '@biomejs/biome': 2.3.8
  astro: 5.16.4
  turbo: 2.6.1
  typescript: 5.9.3

onlyBuiltDependencies:
  - '@sentry/cli'
  - esbuild
  - sharp

patchedDependencies:
  '@gorhom/bottom-sheet': patches/@gorhom__bottom-sheet.patch
