packages:
  - native
  - mono/apps/*
  - mono/docs/*
  - mono/examples/*

catalog:
  '@biomejs/biome': 2.2.6
  astro: 5.15.4
  turbo: 2.5.8
  "@biomejs/biome": 2.3.4
  typescript: 5.9.3

onlyBuiltDependencies:
  - '@sentry/cli'
  - esbuild
  - sharp
