packages:
  - native
  - mono/apps/*
  - mono/docs/*
  - mono/examples/*

catalog:
  typescript: 5.9.3
  astro: 5.14.5
  turbo: 2.5.8
  "@biomejs/biome": 2.3.1

onlyBuiltDependencies:
  - '@sentry/cli'
  - esbuild
  - sharp
