packages:
  - native
  - mono/apps/*
  - mono/docs/*

catalog:
  '@biomejs/biome': 2.4.0
  astro: 5.17.2
  turbo: 2.8.9
  typescript: 5.9.3

onlyBuiltDependencies:
  - '@sentry/cli'
  - esbuild
  - sharp

overrides:
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
