on: 
    push:
        paths: 
            - 'docs/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        deployments: write
    name: Deploy
    steps:
        - uses: actions/checkout@v4.1.1
        - uses: pnpm/action-setup@v2.4.0
          with:
            version: 8.12.1
        - name: install dependencies
          run: pnpm install --frozen-lockfile
        - name: build
          run: pnpm build
        - name: publish docs
          uses: cloudflare/pages-action@v1.5.0
          with:
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            projectName: gg-docs
            directory: docs/starlight/dist # e.g. 'dist'
            gitHubToken: ${{ secrets.GITHUB_TOKEN }}
