name: deploy-gg-landing-site

on:
  push:
    paths:
      - "mono/apps/site/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TURBO_URL: ${{ secrets.TURBO_URL }}
      TURBO_CODE: ${{ secrets.TURBO_CODE }}
    defaults:
      run:
        working-directory: mono
    permissions:
      contents: read
      deployments: write
    name: Deploy
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.12.1
      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: build
        run: cd apps/site && pnpm build:ci
      - name: publish docs
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: gg-landing-site
          directory: mono/apps/site/dist 
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
