on: 
    push:
        paths: 
            - 'gg-mono/docs/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TURBO_URL: ${{ secrets.TURBO_URL }}
      TURBO_CODE: ${{ secrets.TURBO_CODE }}
    defaults:
      run:
        working-directory: gg-mono
    permissions:
        contents: read
        deployments: write
    name: Deploy
    steps:
        - uses: actions/checkout@v4.1.1
        - name: Set up Node.js
          run: corepack enable pnpm
        - uses: actions/setup-node@v4.0.2
          with:
            node-version: 20
            cache: "pnpm"
        - name: install dependencies
          run: pnpm install --frozen-lockfile
        - name: build
          run: cd docs/starlight && pnpm build:ci
        - name: publish docs
          uses: cloudflare/pages-action@v1.5.0
          with:
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            projectName: gg-docs
            directory: gg-mono/docs/starlight/dist # e.g. 'dist'
            gitHubToken: ${{ secrets.GITHUB_TOKEN }}
