name: main-ci

on:
    push:

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      TURBO_URL: ${{ secrets.TURBO_URL }}
      TURBO_CODE: ${{ secrets.TURBO_CODE }}
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: pnpm/action-setup@v3.0.0
        with:
          version: 8.15.1
      - name: install dependencies
        run: cd gg-mono && pnpm install --frozen-lockfile
      - name: lint
        run: cd gg-mono && pnpm lint
      - name: format
        run: cd gg-mono && pnpm format:check
      - name: build
        run: cd gg-mono && pnpm build:ci
      - name: install dependencies
        run: cd native_gg && pnpm install --frozen-lockfile
      - name: lint
        run: cd native_gg && pnpm lint
      - name: format
        run: cd native_gg && pnpm format:check
     