name: ishtar-ci

on:
    push:
    pull_request:
        branches:
        - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.15
      - name: install dependencies
        run: bun install
      - name: lint
        run: bun run lint
      - name: format
        run: bun run format:check
      - name: build
        run: bun run build