name: main-ci

on:
  push:

jobs:
  main-ci-mono:
    name: Main CI Mono
    timeout-minutes: 5
    runs-on: ubuntu-latest

    env:
      TURBO_URL: ${{ secrets.TURBO_URL }}
      TURBO_CODE: ${{ secrets.TURBO_CODE }}

    steps:
      - uses: actions/checkout@v4.1.1
      - uses: pnpm/action-setup@v3.0.0
        with:
          version: 8.15.3
      - name: install dependencies
        run: cd mono && pnpm install --frozen-lockfile
      - name: lint
        run: cd mono && pnpm lint
      - name: format
        run: cd mono && pnpm format:check
      - name: build
        run: cd mono && pnpm build:ci

  main-ci-native:
    name: Main CI native
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - uses: pnpm/action-setup@v3.0.0
        with:
          version: 8.15.3
      - name: install dependencies
        run: cd native_gg && pnpm install --frozen-lockfile
      - name: lint
        run: cd native_gg && pnpm lint
      - name: format
        run: cd native_gg && pnpm format:check
      - name: type check
        run: cd native_gg && pnpm type-check
