name: ishtar-ci

on:
    pull_request:
        branches:
        - main

jobs:
  build:
    name: build
    runs-on: macos-13
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.12.1
      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: lint
        run: pnpm lint
      - name: format
        run: pnpm format:check
      - name: build
        run: pnpm build